app_admon/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from app_admon.forms import LoginForm

urlpatterns = [
    path('', views.Index, name="index"),

    path('accounts/login/', auth_views.LoginView.as_view(
       authentication_form=LoginForm,
       ), name="login"),

    path('inicio/', views.inicioView, name='inicio'),
    
    path('clientes/', views.clientesView, name='clientes'),
    path('add_cliente/', views.add_clienteView, name='add_cliente'),
    
    path('colaboradoras/', views.colaboradorasView, name='colaboradoras'),
]

fiorella/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("app_admon.urls")),
    path('admin/', admin.site.urls)
]

app_admon/models.py
from django.db import models

# Create your models here.
class C_status(models.Model):
    status = models.CharField(max_length=10)

class Cliente(models.Model):
    ced_rif = models.CharField(max_length=10)
    nombre = models.CharField(max_length=40)
    telefono = models.CharField(max_length=11)
    direccion = models.TextField(max_length=200)
    instagram = models.CharField(max_length=40)
    nacimiento = models.DateField(null=True)
    creado = models.DateTimeField(auto_now_add=True, null=False)
    status = models.ForeignKey(C_status, on_delete=models.CASCADE, default=2)
    
    # que valor va a retornar al llamar el objeto
    def __str__(self) -> str:
        return self.nombre

class Prefijo_telefono(models.Model):
    prefijo_t = models.CharField(max_length=4)

    def __str__(self):
        return self.prefijo_t
    
class Prefijo_ced_rif(models.Model):
    prefijo_r = models.CharField(max_length=1)

    def __str__(self):
        return self.prefijo_r    
 
class Servicio(models.Model):
    especialidad = models.CharField(max_length=4)

    def __str__(self):
        return self.especialidad



class Colaborador(models.Model):
    ced_rif = models.CharField(max_length=10)
    nombre = models.CharField(max_length=40)
    telefono = models.CharField(max_length=11)
    direccion = models.TextField(max_length=200)
    instagram = models.CharField(max_length=40)
    nacimiento = models.DateField(null=True)
    creado = models.DateTimeField(auto_now_add=True, null=False)
    status = models.ForeignKey(C_status, on_delete=models.CASCADE, default=2)
    Servicio = models.ManyToManyField(Servicio)

    
    # que valor va a retornar al llamar el objeto
    def __str__(self) -> str:
        return self.nombre

app_admon/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import DateField, DateInput, FloatField, ModelForm
from app_admon.models import *

class DateInput(forms.DateInput):
    input_type = 'Date'

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
             visible.field.widget.attrs['class'] = 'form-control'
             visible.field.widget.attrs['placeholder'] = visible.field.label

class Agregar_clienteForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(Agregar_clienteForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['telefono'].widget.attrs.update(
            {'maxlength': '7', 'minlength': '7',
             'onkeypress': "return soloNumeros(event)"
             })
        self.fields['ced_rif'].widget.attrs.update(
            {'maxlength': '9'})
        self.fields['direccion'].widget.attrs['rows'] = 3
    #     self.fields['nacimiento'].widget.attrs.update(
    #         {'style': 'width: 340px'})
         
    ced_rif = forms.CharField(widget=forms.TextInput(attrs={'style': 'border-left: 0px;border-radius: 0px 25px 25px 0px'}))
    telefono = forms.CharField(widget=forms.TextInput(attrs={'style': 'border-left: 0px;border-radius: 0px 25px 25px 0px'}))
    nacimiento = forms.DateField(widget=DateInput)
      
    
    # nacimiento = forms.DateField(widget=forms.DateInput(attrs={'style': 'width: 305px'}))
       
    class Meta:
        model = Cliente
        fields = ('ced_rif','nombre', 'telefono', 'instagram', 'direccion', 'nacimiento', 'status')
        # widgets = {
        #      'nacimiento': DateInput(format=('%Y-%m-%d'))
         #  }

    

app_admon/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from app_admon.models import *
from app_admon.forms import *

def Index(request):
    return render(request, 'app_admon/index.html')

@login_required
def inicioView(request):
    xAcceso = "Administrador"
    xUsuario = request.user
    context = {
        'xUsuario': request.user,
        }
    return render(request, 'app_admon/inicio.html', context)


@login_required
def clientesView(request):
    xUsuario = request.user

    xClientes = Cliente.objects.values('id','ced_rif','nombre','telefono','instagram','nacimiento','status__status').filter(status=2)
    
    context = {
        'xUsuario': xUsuario,
        'xClientes': xClientes
    }
    return render(request, 'app_admon/clientes.html', context)

@login_required
def add_clienteView(request):
    xUsuario = request.user
    #xCondominios = xUsuario.profile.condominios.all()

    xOpcion = "Agregando"
    xPrefijos_ced_rif = Prefijo_ced_rif.objects.all()
    xPrefijos = Prefijo_telefono.objects.all()
       
    form = Agregar_clienteForm()

    if request.method == 'POST':
        form = Agregar_clienteForm(request.POST)

        #for field in form:
        #   print("Field:", field.name, "-> ", field.errors)

        #print("------------------------ POST ---------------------")
        #print(request.POST)
        #print("------------------------ POST ---------------------")
            
        if form.is_valid():
            cliente = form.save(commit=False)
            cliente.ced_rif = request.POST.get('prefijo_r') + request.POST.get('ced_rif')
            cliente.telefono = request.POST.get('prefijo') + request.POST.get('telefono')
            cliente.save()
            return redirect('clientes')
        else:
            messages.error(
                request, "Su operación no se puedo efectuar debido a problemas en el Servidor. El formulario no es válido")
    
    context = {
     'form': form,
        'xOpcion': xOpcion,
        
        'xPrefijos_ced_rif':xPrefijos_ced_rif,
        'xPrefijos':xPrefijos,
       
    }
    return render(request, 'app_admon/cliente_crud.html', context)

@login_required
def colaboradorasView(request):
    xUsuario = request.user

    xColaboradoras = Colaborador.objects.values('id','ced_rif','nombre','telefono','instagram','nacimiento','status__status').filter(status=2)
    
    context = {
        'xUsuario': xUsuario,
        'xColaboradoras': xColaboradoras
    }
    return render(request, 'app_admon/colaboradoras.html', context)

app_admon/templates/app_admon/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>
    {% block title %}
    {% endblock %}
  </title>
  <meta content="" name="">
  <meta content="" name="">
  <!-- Favicons icono de la pestaña -->
  <link href="{% static 'app_admon/custom-files/img/difuminado.jpg' %}" rel="icon">

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'app_admon/custom-files/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'app_admon/custom-files/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'app_admon/custom-files/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'app_admon/custom-files/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'app_admon/custom-files/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'app_admon/custom-files/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'app_admon/custom-files/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Estilos CSS Personalizados -->
  <link href="{% static 'app_admon/custom-files/css/style.css' %}" rel="stylesheet" type="text/css">

  <!-- Estilos iconos de login y register -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

  <!-- Estilos adicionales de pagina hija-->
  {% block styles %}
  {% endblock styles %}
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
      <span href="#" class="logo d-flex align-items-center">
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <span class="d-none d-lg-block">Fiorella Beauty</span>
      </span>
      <!-- <i class="bi bi-list toggle-sidebar-btn" style="color: black"></i>-->
    </div><!-- End Logo -->
    
  </header><!-- End Header -->


  <!-- ======= Content incio del block content en base.html ======= -->
  {% block content %}
  {% endblock content %}
  <!-- Fin del block content  -->

  <!-- ======= Footer ======= -->
  {% include 'app_admon/footer.html' %}
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'app_admon/custom-files/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'app_admon/custom-files/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'app_admon/custom-files/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'app_admon/custom-files/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'app_admon/custom-files/vendor/quill/quill.js' %}"></script>
  <script src="{% static 'app_admon/custom-files/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'app_admon/custom-files/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'app_admon/custom-files/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'app_admon/custom-files/js/main.js' %}"></script>

    <!-- Archivos JS adicionales de paginas hijas -->
    {% block Scripts_Adicionales %}
    {% endblock Scripts_Adicionales %}
</body>

</html>

app_admon/templates/app_admon/cliente_crud.html
{% extends "app_admon/layout.html" %}
{% block title %}
Atico | Cliente_crud
{% endblock %}
{% block styles %}
{% endblock styles %}
{% block content %}
<main id="main" class="main ">

    <div class="card fondo-difuminado">
        <div class="card-body" style="padding: 10px 80px 10px 80px;">
        <!-- Emcabezado-->
        <div class="row" style="padding-top: 30px;">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <h5 align="center" class="h5-suave margen-bottom"> {{ xOpcion }} Cliente </h5>
            </div>
            <div class="col-md-4 text-right">
                <a href="javascript:history.back()" class="float-end">
                    <i class="fas fa-angle-left fa-lg h" title='Ir atras'></i>
                </a>
            </div>
        </div>

        <form id="cliente_crud" action="" style="padding-top: 10px;" method="post">
            {% csrf_token %}
            <!-- ------------------------------------ Agregando ------------------------------------- -->
             {% if xOpcion == 'Agregando' %}
             <!-- 1ra fila -->
             <div class="row" style="margin-bottom: 10px">
                 <div class="col-md-6">
                     <span class="titulos">Cédula/Rif</span><br>
                     <div class="col-md-12 d-flex">
                         <select name="prefijo_r" id="prefijo_r" class="form-control ho"
                             style="width: 105px ;border-radius: 25px 0px 0px 25px" required>
                             <option id="-1" value="">Seleccione</option>
                             {% for xPre_ced_rif in xPrefijos_ced_rif %}
                             <option id={{xPre_ced_rif}}>
                                  {{xPre_ced_rif}}
                             </option>
                             {% endfor %}
                         </select>
                             {{form.ced_rif}}
                     </div>
                 </div>
                 <div class="col-md-6">
                     <span class="titulos">
                         {{form.nombre.label}}</span>
                     {{form.nombre}}
                 </div>
             </div>
             <!-- 2da fila -->
             <div class="row" style="margin-bottom: 10px">
                 <div class="col-md-6">
                     <span class="titulos">Télefono</span><br>
                     <div class="col-md-12 d-flex">
                        
                         <select name="prefijo" id="prefijo" class="form-control ho" 
                            style="width: 105px; border-radius: 25px 0px 0px 25px" required>
                             <option id="-1" value="">Seleccione</option>
                             {% for xPre_telefono in xPrefijos %}
                             <option id={{xPre_telefono}}>
                                  {{xPre_telefono}}
                             </option>
                             {% endfor %}
                         </select>
                         {{form.telefono}}
                    </div>
                 </div>
                 <div class="col-md-6">
                     <span class="titulos">
                         {{form.instagram.label}}</span>
                     {{form.instagram}}
                 </div>
             </div>
             <!-- 3ra fila -->
             <div class="row" style="margin-bottom: 10px">
                 <div class="col-md-6">
                     <span class="titulos">
                         {{form.nacimiento.label}}</span>
                         {{form.nacimiento}}
                 </div>
                 <div class="col-md-6">
                     <span class="titulos">
                         {{form.direccion.label}}</span>
                     {{form.direccion}}
                 </div>
             </div>

             <input type="text" name="status" value=2 hidden>
           
             {% endif %}
             <!-- ------------------------------------ Editando ------------------------------------- -->
             {% if xOpcion == 'Editando' %}
             <!-- 1ra fila -->
             <div class="row" style="margin-bottom: 10px; ">
                 <div class="col-md-6">
                     <span class="titulos"></span><span id="hoy" class="boton-ajustado-a-la-derecha">HOY</span>
                     {{form.fecha.label}}</span>
                     {{form.fecha}}<span id="fecha_validation_msg" class="validation-msg" hidden>La Fecha no
                         corresponde
                         al año seleccionado</span>
                 </div>
                 <div class="col-md-6">
                     <span class="titulos">Cédula/Rif</span><br>
                     <div class="col-md-3 float-start">
                         <select name="prefijo_r" id="prefijo_r" class="form-control float-start"
                             style="border-right: 0px" required>
                             <option id="-1" value="">Seleccione</option>
                             {% for xPre_ced_rif in xPrefijos_ced_rif %}
                             <option id={{xPre_ced_rif}} value="{{xPre_ced_rif}}" {% if xPre_ced_rif.prefijo_r == rPre %}
                                 selected {% endif %}> {{xPre_ced_rif}}
                             </option>
                             {% endfor %}
                         </select>
                     </div>
                     <div class="col-md-9 float-start">
                         <input type="text" name="ced_rif" value={{rCed_rif}} maxlength="9" class="form-control"
                             onkeypress="Ocultar_validation_msg('ced_rif_validation_msg')" required id="id_ced_rif"><span
                             id="ced_rif_validation_msg" class="validation-msg" hidden>Esta Cédula/Rif ya esta rigistrada</span>
                     </div>
                 </div>
             </div>
             <!-- 2da fila -->
             <div class="row" style="margin-bottom: 10px">
                 <div class="col-md-6">
                     <span class="titulos">
                         {{form.nombre.label}}</span>
                     {{form.nombre}}
                 </div>
                 <div class="col-md-6">
                     <span class="titulos">Télefono</span><br>
                     <div class="col-md-3 float-start">
                         <select name="prefijo" id="prefijo" class="form-control float-start" style="border-right: 0px" required>
                             <option id="-1" value="">Seleccione</option>
                             {% for xPre_telefono in xPrefijos %}
                             <option id={{xPre_telefono}} value="{{xPre_telefono}}" {% if xPre_telefono.prefijo_t == rPre_t %} selected {% endif %}>
                                  {{xPre_telefono}}
                             </option>
                             {% endfor %}
                         </select>
                     </div>
                     <div class="col-md-9 float-start">
                         <input type="text" name="telefono" value="{{rTelefono}}" minlength="7" maxlength="7" class="form-control"
                             onkeypress="return soloNumeros(event)" required id="id_telefono">
                     </div>
                 </div>
             </div>
             <!-- 3ra fila -->
             <div class="row" style="margin-bottom: 10px">
                 <div class="col-md-6">
                     <span class="titulos">
                         {{form.contacto.label}}</span>
                     {{form.contacto}}
                 </div>
                 <div class="col-md-6">
                     <span class="titulos">Télefono contacto</span><br>
                     <div class="col-md-3 float-start">
                         <select name="prefijo_c" id="prefijo_c" class="form-control float-start"
                             style="border-right: 0px" required>
                             <option id="-1" value="">Seleccione</option>
                             {% for xPre_telefono_c in xPrefijos %}
                             <option id={{xPre_telefono_c}} value="{{xPre_telefono_c}}" {% if xPre_telefono_c.prefijo_t == rPre_c %} selected {% endif %}>
                                  {{xPre_telefono_c}}
                             </option>
                             {% endfor %}
                         </select>
                     </div>
                     <div class="col-md-9 float-start">
                         <input type="text" name="telefono_c" value="{{rTelefono_c}}" minlength="7" maxlength="7" class="form-control"
                             onkeypress="return soloNumeros(event)" required id="id_telefono_c">
                     </div>
                 </div>
             </div>
             <!-- 4ta fila  -->
             <div class="row" style="margin-bottom: 10px">
                 <div class="col-md-6 mt-3 mt-md-0">
                     <span class="titulos">
                         {{form.direccion.label}}</span>
                     {{form.direccion}}
                 </div>
              
                 <div class="col-md-6 mt-3 mt-md-0">
                     <span class="titulos">Ciudad</span>
                     <select name="ciudad" id="ciudad" class="form-control" required>
                         <option id="-1" value="">Seleccione un elemento</option>
                         {% for xCiudad in xCiudades %}
                         <option id={{xCiudad.id}} value="{{xCiudad.id}}" {% if xCiudad.id == rCiudadId %} selected {% endif %}>
                             {{xCiudad}}
                         </option>
                         {% endfor %}
                     </select>
                 </div>
             </div>
             <!-- 5ta fila  -->
             <div class="row" style="margin-bottom: 10px">
                 <div class="col-md-6 mt-3 mt-md-0">
                     <span class="titulos">Rama</span>
                     <select name="rama" id="rama" class="form-control" required>
                         <option id="-1" value="">Seleccione un elemento</option>
                         {% for xRama in xRamas %}
                         
                         <option id={{xRama.id}} value="{{xRama.id}}" {% if xRama.id == rRamaId %} selected {% endif %}>
                             {{xRama}}
                         </option>
                         
                         {% endfor %}
                     </select>
                 </div>
             </div>
             {% endif %}
             <!-- Botones -->
             <div style="padding:20px 0px" class="text-end">
                 <button class="btn btn-dark rounded-pill" type="button" style="margin-right: 15px;" onclick="javascript:history.back()">Descartar</button>
                 {% if xOpcion == 'Eliminando' %}
                 <button type="button">
                     Eliminar</button>
                 {% else %}
                 <button type="submit" class="btn btn-dark rounded-pill" id="guardar" onclick="validar(event)">
                     Guardar</button>
                 {% endif %}
             </div>
           </form>


        </div>
    </div>

</main>
{% endblock content %}
<!-- Java Script -->
{% block Scripts_Adicionales %}
<script>
    // Funcion para validar formulario


    // Eliminar         
    function eliminar(e) {
        e.preventDefault();
        Swal.fire({
            title: '¿ Esta seguro de eliminar ?',
            //text: ': ',
            icon: 'question',
            showCancelButton: true,
            cancelButtonText: 'Descartar' + '&nbsp;&nbsp;' + 'X',
            confirmButtonText: 'Confirmar' + '&nbsp;&nbsp;' + '√',
            position: 'bottom',
            allowOutsideClick: false,
            allowEnterKey: false,
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById('proveedor_crud').submit();
            }
        })
    };
</Script>
{% endblock Scripts_Adicionales %}

app_admon/templates/app_admon/clientes.html
{% extends "app_admon/layout.html" %}
{% load static %}

{% block title %}
Fiorella | Clientes
{% endblock %}

{% block styles %}
{% endblock styles %}

{% block content %}
<main id="main" class="main fondo-difuminado">
    <!-- <div id="idmenu" class="container-min-height" data-menu="m2"> -->
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <h5 align="center" class="h5-suave">Clientes</h5>
            </div>
            <div class="col-md-4">
                <a href="{% url 'inicio' %}" class="float-end">
                    <i class="bi bi-x-circle-fill h4 h" title='Cerrar'></i>
                </a>
            </div>
        </div>
        <div class="text-center">
            <a href="{% url 'add_cliente' %}">
            <i class="bi-person-plus-fill h4 h" title='Agregar nuevo registro'></i>
            </a>
            
        </div>
        <table id="clientes" class="table  table-bordered table-hover " style="width:100%">
            <thead>
                <tr>
                    
                    <th>CED/RIF</th>
                    <th style="width:300px">NOMBRE</th>
                    <th>TELEFONO</th>
                    <th>INSTAGRAM</th>
                    <th>F. NACIMIENTO</th>
                    <th>STATUS</th>
                    <th>EDITAR</th>


                    
                </tr>
            </thead>
            <tbody>
                
                {% for xCliente in xClientes %}
                <tr>
                    <td>{{xCliente.ced_rif}}</td>
                    <td>{{xCliente.nombre|truncatechars:22}}</td>
                    <td>{{xCliente.telefono}}</td>
                    <td>{{xCliente.instagram}}</td>
                    <td>{{xCliente.nacimiento}}</td>
                    <td>{{xCliente.status__status}}</td>
                    <td class="text-center" style="width:50px">
                        <a  href="#">
                            <i class="fas fa-pencil-alt h"></i>
                        </a>
                        
                    </td>
                
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
            </tfoot>
        </table>
    <!-- </div> -->
</main>

{% endblock content %}

{% block Scripts_Adicionales %}
<script>
    $(function () {
        $("#clientes").DataTable({
            language: {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "*** No se encontró información ***",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                },
                "buttons": {
                    "copy": "Copiar",
                    "colvis": "Visibilidad"
                }
            },
            "responsive": true,
            "lengthChange": true,
            "autoWidth": true,
            "pageLength": 50,
           
            "order": [[1, "asc"]],
            "columnDefs": [{
                "targets": [0, 2, 3 ],
                "orderable": false
            }]


        })
    });


    // tool tip
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))

</script>
{% endblock Scripts_Adicionales %}

app_admon/templates/app_admon/footer.html
  
  <footer id="footer" class="footer2">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

app_admon/templates/app_admon/index.html
<!--
Page...: index.html:
Father.: base.html
Content: carrusel de imagenes de marketing
-->
{% extends 'app_admon/base.html' %}
{% load static %}

{% block title %}
Fiorella | Index
{% endblock %}

{% block content %}

<main id="main2" class="main fondo-difuminado">
  
  <div class="row" style="padding-top: 220px;">
    <div class="col-5">
    </div>

    <div class="col-2 text-center" style="width: 100%;">
      <br>
      <h1 align="center"><span id="saludo" ></span></h1>
      <h5 align="center"><span id="f"></span></h5>
      <h2 class="clockf"><span id="h"></span></h2>

      <a href="{% url 'login' %}" class="a-btn">Ingresar</a>
    </div>

    <div class="col-5">
    </div>
  </div>

</main><!-- End #main -->

{% endblock content %}
{% block Scripts_Adicionales %}
<script>
// Funciones para mostra la hora
        mostrar_hora();
        repetirCadaMinuto();

        // Funcion feha y hora
        function mostrar_hora() {
        
            let hoy = new Date();
            let options = {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            };
            let fecha = hoy.toLocaleString(undefined, options);
            if (hoy.getMinutes() < 10) {
                hoyMin = hoy.getMinutes();
                let minString = hoyMin.toString();
                var min = "0" + minString;
            }
            else {
                var min = hoy.getMinutes();
            }
            let hora = hoy.getHours() + ':' + min;
            let ho = hoy.getHours()
            h.innerHTML = hora;
            f.innerHTML = fecha;
            if (ho >= 12) {
                document.getElementById("saludo").innerHTML = "!Buenas tardes!";
                if (ho >= 18) {
                    document.getElementById("saludo").innerHTML = "!Buenas noches!";
                }
            } else {
                document.getElementById("saludo").innerHTML = "!Buenos dias!";
            }
        }
        // Funcion para recargara la hora
        function repetirCadaMinuto() {
            identificadorIntervaloDeTiempo = setInterval(() => {
                mostrar_hora();
            }, 60 * 1000);
        }
      </script>
      {% endblock Scripts_Adicionales %}

app_admon/templates/app_admon/list_errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
</div>

{% endfor %}
{% endif %}

app_admon/templates/app_admon/mensajes.html
<div class="row mt-3">
    <div class="col-12">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-dismissible fade show erro-en-backend" role="alert">
                    <h3 align="center" style="color: red;">¡Ocurrió un error!</h3>
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>